# Generated by Django 3.0.8 on 2021-04-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college_player',
            name='ass_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='college_player',
            name='blo_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='college_player',
            name='games',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='college_player',
            name='min_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='college_player',
            name='poi_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='college_player',
            name='rank',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='college_player',
            name='reb_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='college_player',
            name='ste_per_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='college_player',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
